version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "gradle"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      gradle:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3
  - package-ecosystem: "cargo"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns: [ "*" ]
    open-pull-requests-limit: 3
