[package]
name = "smithy4rs-schema"
description = "Smithy Schema definitions for smithy4rs."
repository.workspace = true
publish = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
num-bigint.workspace = true
bigdecimal.workspace = true
bytebuffer.workspace = true
indexmap.workspace = true
thiserror.workspace = true
downcast-rs = "2.0.1"
triomphe = "0.1.14"