[env]
# needed because the 2 rust versions installed by mise may be switched around
RUSTUP_TOOLCHAIN="stable"

[tools]
# We need cargo-binstall so that Mise would download "cargo:" tools instead of building them.
cargo-binstall = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-criterion" = "latest"
"cargo:cargo-sort" = "latest"
rust = [
    { profile = "minimal", version = "nightly", components = "rustfmt" },
    { profile = "default", version = "1.90.0", components = "clippy" }
]

[tasks.build]
description = "Build the project"
run = "cargo build"

[tasks.fmt-all]
wait_for = ["build", "lint", "test", "check-bench"]
description = "Check the code format"
run = [
    "cargo +nightly fmt --all --",
    "cargo sort"
]

[tasks.lint]
wait_for = ["test"]
depends = ["build"]
description = "Lint the code with Clippy"
env = { RUST_BACKTRACE = '1' }
run = "cargo clippy --workspace --all-targets"

[tasks.audit]
wait_for = ["build", "lint", "test", "fmt-all", "check-bench"]
description = "Audit Dependencies"
run = "cargo deny check"

[tasks.test]
wait_for = ["build"]
description = "Tests the library"
run = "cargo nextest run --locked"

[tasks.clean]
description = "Remove build artifacts"
run = "cargo clean"

[tasks.check-bench]
wait_for = ["test", "lint"]
description = "Tests the benchmarks"
run = "cargo criterion --no-run"

[tasks.bench]
depends = ["build"]
description = "Runs benchmarks"
run = "cargo criterion --plotting-backend disabled --all-features"

[tasks.pre-push]
description = "Check that project will pass CI checks"
depends = ['build', 'lint', 'audit', 'test', 'fmt-all', 'check-bench']
